# Generated by Django 5.1.6 on 2025-02-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFile',
        ),
    ]
